linters:
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell

linters-settings:
  govet:
    check-shadowing: true
  revive:
    confidence: 0.8
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - "vendor"
    - "..*"
    - ".*go/pkg/mod"
    - ".*go/src"

issues:
  exclude-rules:
    - path: ".*_test\\.go"
      linters:
        - errcheck
        - dupl
        - gosec
        - gocyclo
        - lll
        - misspell
        - goconst
        - gomnd
