name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      # - name: Run linter
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     version: v1.54

      - name: Run tests
        run: go test ./...

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o main ./cmd/api
