name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build Go binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o main ./cmd/api

      - name: Package app for EB
        run: |
          zip -r app.zip main .ebextensions

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: gymshark-api
          environment_name: gymshark-api-env
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: app.zip
